/*
* ============================================================================
*  Name     : CSplashView from SplashView.h
*  Part of  : SplashView
*  Created  : 12/2/2003 by pawel@wapice.com	
*  Implementation notes:
*     Initial content was generated by Nokia Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  "SplashView.h"
#include  "SplashContainer.h" 
#include  "TOPGUNAppUi.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSplashView::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CSplashView::ConstructL()
    {
    BaseConstructL();
    }

// ---------------------------------------------------------
// CSplashView::~CSplashView()
// 
// ---------------------------------------------------------
//
CSplashView::~CSplashView()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
	iContainer = NULL;
    }


// ---------------------------------------------------------
// TUid CSplashView::Id()
// 
// ---------------------------------------------------------
//
TUid CSplashView::Id() const
    {
    return KView3Id;
    }

// ---------------------------------------------------------
// CSplashView::HandleCommandL(TInt aCommand)
// 
// ---------------------------------------------------------
//
void CSplashView::HandleCommandL(TInt aCommand)
    {
	AppUi()->HandleCommandL( aCommand );
    }

// ---------------------------------------------------------
// CSplashView::HandleClientRectChange()
// ---------------------------------------------------------
//
void CSplashView::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CSplashView::DoActivateL()
// 
// ---------------------------------------------------------
//
void CSplashView::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CSplashContainer;
        iContainer->SetMopParent(this);
        iContainer->ConstructL(AppUi()->ApplicationRect());
		iContainer->SetView(this);
        AppUi()->AddToStackL( *this, iContainer );
        }
   }

// ---------------------------------------------------------
// CSplashView::HandleCommandL(TInt aCommand)
//
// ---------------------------------------------------------
//
void CSplashView::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CSonarBlueView::SetAppUi(CSonarBlueAppUi* aAppUi)
// ?implementation_description
// ---------------------------------------------------------
//
void CSplashView::SetAppUi(CTOPGUNAppUi* aAppUi, CAknTabGroup* aTabGroup)
	{
	iAppUi = aAppUi;
	iTabGroup = aTabGroup;
	}

void CSplashView::SwitchView()
	{
	iAppUi->RunGameFirstTimeL();
	iAppUi->SwitchView(3);
	}

// End of File

