/*
* ============================================================================
*  Name     : CSplashView1 from SplashView1.h
*  Part of  : SplashView1
*  Created  : 12/2/2003 by pawel@wapice.com	
*  Implementation notes:
*     Initial content was generated by Nokia Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  "SplashView1.h"
#include  "SplashContainer1.h" 
#include  "TOPGUNAppUi.h"


// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSplashView1::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CSplashView1::ConstructL()
    {
    BaseConstructL();
    }

// ---------------------------------------------------------
// CSplashView1::~CSplashView1()
// 
// ---------------------------------------------------------
//
CSplashView1::~CSplashView1()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
	iContainer = NULL;
    }


// ---------------------------------------------------------
// TUid CSplashView1::Id()
// 
// ---------------------------------------------------------
//
TUid CSplashView1::Id() const
    {
    return KView4Id;
    }

// ---------------------------------------------------------
// CSplashView1::HandleCommandL(TInt aCommand)
// 
// ---------------------------------------------------------
//
void CSplashView1::HandleCommandL(TInt aCommand)
    {
	AppUi()->HandleCommandL( aCommand );
    }

// ---------------------------------------------------------
// CSplashView1::HandleClientRectChange()
// ---------------------------------------------------------
//
void CSplashView1::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CSplashView1::DoActivateL()
// 
// ---------------------------------------------------------
//
void CSplashView1::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CSplashContainer1;
        iContainer->SetMopParent(this);
        iContainer->ConstructL(AppUi()->ApplicationRect());
		iContainer->SetView(this);
        AppUi()->AddToStackL( *this, iContainer );
        }
   }

// ---------------------------------------------------------
// CSplashView1::HandleCommandL(TInt aCommand)
//
// ---------------------------------------------------------
//
void CSplashView1::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CSonarBlueView::SetAppUi(CSonarBlueAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
void CSplashView1::SetAppUi(CTOPGUNAppUi* aAppUi, CAknTabGroup* aTabGroup)
	{
	iAppUi = aAppUi;
	iTabGroup = aTabGroup;
	}

void CSplashView1::SwitchView()
	{
	iAppUi->SwitchView(0);
	}

// End of File

