/*
* ============================================================================
*  Name     : CTOPGUNView5 from TOPGUNView5.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include "topgun.hrh"
#include  "TOPGUNView5.h"
#include  "TOPGUNContainer5.h" 
#include  "TOPGUNAppUi.h" 
// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView5::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CTOPGUNView5::ConstructL()
    {
    BaseConstructL();
    }

// ---------------------------------------------------------
// CTOPGUNView5::~CTOPGUNView5()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView5::~CTOPGUNView5()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView5::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView5::Id() const
    {
    return KView7Id;
    }

// ---------------------------------------------------------
// CTOPGUNView5::HandleCommandL(TInt aCommand)
// takes care of View5 command handling
// ---------------------------------------------------------
//
void CTOPGUNView5::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView5::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView5::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView5::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView5::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer5;
        iContainer->SetMopParent(this);
        iContainer->ConstructL(AppUi()->ApplicationRect());
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView5::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView5::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CTOPGUNView5::SetAppUi(CTOPGUNAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
void CTOPGUNView5::SetAppUi(CTOPGUNAppUi* aAppUi)
	{
	iAppUi = aAppUi;
	}

// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView5::SwitchView(TInt aIndex)
	{
	if (iAppUi)
		{
		iAppUi->SwitchView(aIndex);	
		}
	}

// End of File

