/*
* ============================================================================
*  Name     : CTOPGUNView9 from TOPGUNView9.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include  "topgun.hrh"
#include  "TOPGUNView9.h"
#include  "TOPGUNContainer9.h"
#include  "TOPGUNAppUi.h"
#include  "LevelLoader.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"  

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView9::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
CTOPGUNView9::CTOPGUNView9(CLevelLoader& aLevelLoader,
						   CTOPGUNAppUi& aAppUi):
	iLevelLoader(aLevelLoader),
	iAppUi(aAppUi)
	{
	BaseConstructL();
	}


void CTOPGUNView9::ConstructL()
    {
    }

// ---------------------------------------------------------
// CTOPGUNView9::~CTOPGUNView9()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView9::~CTOPGUNView9()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView9::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView9::Id() const
    {
    return KView11Id;
    }

// ---------------------------------------------------------
// CTOPGUNView9::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView9::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView9::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView9::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView9::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView9::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer9(iLevelLoader,*iAppUi.GetDocument(),*this);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect());
        AppUi()->AddToStackL( *this, iContainer );
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView9::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView9::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView9::SwitchView(TInt aIndex)
	{
	iAppUi.SwitchView(aIndex);	
	}


// End of File

