/*
* ============================================================================
*  Name     : CTOPGUNView6 from TOPGUNView6.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include  "topgun.hrh"
#include  "TOPGUNView6.h"
#include  "TOPGUNContainer6.h"
#include  "TOPGUNAppUi.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"  

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView6::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CTOPGUNView6::ConstructL()
    {
    BaseConstructL();
    }

// ---------------------------------------------------------
// CTOPGUNView6::~CTOPGUNView6()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView6::~CTOPGUNView6()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView6::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView6::Id() const
    {
    return KView8Id;
    }

// ---------------------------------------------------------
// CTOPGUNView6::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView6::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView6::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView6::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView6::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView6::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer6;
        iContainer->SetMopParent(this);
        iContainer->ConstructL(AppUi()->ApplicationRect());
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView6::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView6::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CTOPGUNView::SetAppUi(CTOPGUNAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
void CTOPGUNView6::SetAppUi(CTOPGUNAppUi* aAppUi)
	{
	iAppUi = aAppUi;
	}

// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView6::SwitchView(TInt aIndex)
	{
	if (iAppUi)
		{
		iAppUi->SwitchView(aIndex);	
		}
	}


// End of File

