/*
* ============================================================================
*  Name     : CTOPGUNApp from TOPGUNApp.cpp
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: P&P
* ============================================================================
*/

// INCLUDE FILES
#include <eikenv.h>
#include <eikproc.h>
#include <EIKAPPUI.H>
#include "TOPGUNApp.h"
#include "TOPGUNDocument.h"

// The file name, extension and path for the file store
_LIT(KFullNameOfFileStore,"C:\\Private\\1027486b\\TOPGUN");
// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CTOPGUNApp::AppDllUid() const
    {
    return KUidTOPGUN;
    }

// ---------------------------------------------------------
// CDictionaryStore* CTOPGUNApp::OpenIniFileLC(RFs& aFs) const
// overrides CAknApplication::OpenIniFileLC to enable INI file support
// ---------------------------------------------------------
//
CDictionaryStore* CTOPGUNApp::OpenIniFileLC(RFs& aFs) const
{
    return CEikApplication::OpenIniFileLC(aFs);
}
   
// ---------------------------------------------------------
// CTOPGUNApp::CreateDocumentL()
// Creates CTOPGUNDocument object
// ---------------------------------------------------------
//
CApaDocument* CTOPGUNApp::CreateDocumentL()
    {
    CApaDocument* document = CTOPGUNDocument::NewL( *this );
    RFs fs;
//    CleanupClosePushL(fs);
    User::LeaveIfError(fs.Connect()); 
    
    CEikProcess* proc = CEikonEnv::Static()->Process();
    CFileStore* store = proc->MainStore();
    if ( !store )
    	{
        store = document->CreateFileStoreLC(fs, KFullNameOfFileStore);
    	}
	// main store
//    CEikDocument* doc = CEikonEnv::Static()->EikAppUi()->Document();
	ASSERT(store);
    proc->SetMainStore(store);
    fs.Close();
    // store
    CleanupStack::Pop(store);
    return document;
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CTOPGUNApp
// Returns: created application object
// ---------------------------------------------------------
//
//EXPORT_C CApaApplication* NewApplication()
//    {
//    return new CTOPGUNApp;
//    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
//GLDEF_C TInt E32Dll( TDllReason )
//    {
//    return KErrNone;
//    }

// End of File  

