/*
* ============================================================================
*  Name     : CTOPGUNView from TOPGUNView.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include "topgun.hrh"
#include  "TOPGUNView.h"
#include  "TOPGUNContainer.h"
#include  "TOPGUNAppUi.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"  

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CTOPGUNView::ConstructL(CSndMixer*	aSndMixer,
							 TSample& aMusicSample,
							 TSample& aSelectSample,
							 TSample& aButtonSample,
							 TInt aAudioVol,
							 TInt aSfxVol)
    {
    BaseConstructL();
	iSndMixer = aSndMixer;
	iMusicSample = aMusicSample;
	iSelectSample = aSelectSample;
	iButtonSample = aButtonSample;
	iAudioVol = aAudioVol;
	iSfxVol = aSfxVol;
    }

// ---------------------------------------------------------
// CTOPGUNView::~CTOPGUNView()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView::~CTOPGUNView()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView::Id() const
    {
    return KViewId;
    }

// ---------------------------------------------------------
// CTOPGUNView::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer;
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect(),
								iSndMixer,
								iMusicSample,
								iSelectSample,
								iButtonSample,
								iAudioVol,
								iSfxVol);
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CTOPGUNView::SetAppUi(CTOPGUNAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
void CTOPGUNView::SetAppUi(CTOPGUNAppUi* aAppUi)
	{
	iAppUi = aAppUi;
	}

// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView::SwitchView(TInt aIndex)
	{
	if (iAppUi)
		{
		iAppUi->SwitchView(aIndex);	
		}
	}

// ----------------------------------------------------
// CTOPGUNAppUi::SetVolume(TInt aSfxVol, TInt aAudioVol)
// 
// ----------------------------------------------------
//
void CTOPGUNView::SetVolume(TInt aSfxVol, TInt aAudioVol)
	{
	iSfxVol = aSfxVol;
    iAudioVol = aAudioVol;
	}

// End of File

