/*
* ============================================================================
*  Name     : CTOPGUNDocument from TOPGUNDocument.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: P&P
* ============================================================================
*/

// INCLUDE FILES
#include <s32file.h>
#include "TOPGUNDocument.h"
#include "TOPGUNAppUi.h"
#include "HighScore.h"
#include "GameSettings.h"

// ================= MEMBER FUNCTIONS =======================

// The file name, extension and path for the file store
_LIT(KFullNameOfFileStore,"C:\\Private\\E0000001\\MyFolder\\TOPGUN_store.dat");


// constructor
CTOPGUNDocument::CTOPGUNDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CTOPGUNDocument::~CTOPGUNDocument()
    {
	iGameSettings.ResetAndDestroy();
	iHighScoreList.ResetAndDestroy();
    }

// EPOC default constructor can leave.
void CTOPGUNDocument::ConstructL()
    {
    }

// Two-phased constructor.
CTOPGUNDocument* CTOPGUNDocument::NewL(
        CEikApplication& aApp)     // CTOPGUNApp reference
    {
    CTOPGUNDocument* self = new (ELeave) CTOPGUNDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CTOPGUNDocument::CreateAppUiL()
// constructs CTOPGUNAppUi
// ----------------------------------------------------
//
CEikAppUi* CTOPGUNDocument::CreateAppUiL()
    {
    return new (ELeave) CTOPGUNAppUi;
    }

// ----------------------------------------------------
// CTOPGUNDocument::OpenFileL
// Overrides CAknDocument::OpenFileL to support document file
// ----------------------------------------------------
//
CFileStore* CTOPGUNDocument::OpenFileL(TBool aDoOpen,const TDesC& aFilename,RFs& aFs)
    {
    return CEikDocument::OpenFileL(aDoOpen, aFilename, aFs);
    }

// ----------------------------------------------------
// CTOPGUNDocument::RestoreL()
// restore data from persistent store
// ----------------------------------------------------
//      
void CTOPGUNDocument::RestoreL(const CStreamStore& aStore, const CStreamDictionary& aStreamDic)
    {
//    RFs fsSession; 
//    TParse  filestorename;
//    fsSession.Parse(KFullNameOfFileStore,filestorename);
//    CFileStore* store = CDirectFileStore::OpenLC(fsSession,filestorename.FullName(),EFileRead);
    // Construct and open the root stream which 
    // contains the representation of our objects.
    RStoreReadStream instream;
    instream.OpenLC(aStore,aStreamDic.At(Application()->AppDllUid()));
    TInt count = instream.ReadInt16L();
    //restore high score
	for (TInt index = 0; index < count; ++index)
        {
        CHighScoreItem* item = CHighScoreItem::NewL();
	    CleanupStack::PushL(item);
        item->InternalizeL(instream);
		User::LeaveIfError(iHighScoreList.Append(item));
	    CleanupStack::Pop(item);
        }

	//restore game settings
	TInt settingsCount = instream.ReadInt16L();
	if(settingsCount)
		{
		CGameSettings* settings = CGameSettings::NewL();
		CleanupStack::PushL(settings);
	    settings->InternalizeL(instream);
		User::LeaveIfError(iGameSettings.Insert(settings,0));
		CleanupStack::Pop(settings);		
		}
	
	CleanupStack::PopAndDestroy();  // stream 
    }

// ----------------------------------------------------
// CTOPGUNDocument::StoreL()
// store data to persistent store
// ----------------------------------------------------
//          
void CTOPGUNDocument::StoreL(CStreamStore& aStore, CStreamDictionary& aStreamDic) const
	{
//	RFs fsSession;
//	fsSession.MkDirAll(KFullNameOfFileStore);
//    TParse  filestorename;
//    fsSession.Parse(KFullNameOfFileStore,filestorename);
//    CFileStore* store = CDirectFileStore::ReplaceLC(fsSession,filestorename.FullName(),EFileWrite);
//    store->SetTypeL(KDirectFileStoreLayoutUid);
    RStoreWriteStream outstream;
    TStreamId id = outstream.CreateLC(aStore);
    outstream.WriteInt16L(iHighScoreList.Count());
    TInt index = 0;
	//store high scores
    for (index = 0; index < iHighScoreList.Count(); ++index)
        {
		iHighScoreList[index]->ExternalizeL(outstream);
        }
	
	//store game settings
	index = 0;
	TInt settingsCount = iGameSettings.Count();
	outstream.WriteInt16L(settingsCount);
	if (settingsCount)
		{
		iGameSettings[index]->ExternalizeL(outstream);
		}
    outstream.CommitL();
    // Cleanup the stream object
    CleanupStack::PopAndDestroy();
    // Commit changes to the store
    aStore.CommitL();
//
	aStreamDic.AssignL(Application()->AppDllUid(), id);
//	CleanupStack::PopAndDestroy(); // stream
	}

void CTOPGUNDocument::InsertHighScoreItemL(CHighScoreItem* aItem, TInt aIndex)
	{
	User::LeaveIfError( iHighScoreList.Insert( aItem, aIndex)  );
	}

void CTOPGUNDocument::SetGameSettingsL(CGameSettings* aSettings, TInt aIndex)
	{
	User::LeaveIfError( iGameSettings.Insert( aSettings, aIndex)  );
	}

void CTOPGUNDocument::RemoveHS(TInt aIndex)
	{
	CHighScoreItem* item = iHighScoreList[aIndex];
	delete item;
	iHighScoreList.Remove(aIndex);
	}

CHighScoreItem* CTOPGUNDocument::HighScoreItem(TInt aIndex)
	{
	CHighScoreItem* item;
	if (iHighScoreList.Count() == 0)
		{
		item = NULL;
		}
	else
		{
		item = static_cast<CHighScoreItem*> (iHighScoreList[aIndex]);
		}
	return item;
	}

CGameSettings* CTOPGUNDocument::GameSettings(TInt aIndex)
	{
	CGameSettings* item;
	if (iGameSettings.Count() == 0)
		{
		item = NULL;
		}
	else
		{
		item = static_cast<CGameSettings*> (iGameSettings[aIndex]);
		}
	return item;
	}

void CTOPGUNDocument::SortHighScoreList()
	{
	//CGameSettings *gs = CGameSettings::NewL();
	//gs = GameSettings(0);

	TLinearOrder<CHighScoreItem> order(CHighScoreItem::CompareTop);
	iHighScoreList.Sort(order);

	//SetGameSettingsL(gs,0);
	}

TBool CTOPGUNDocument::CheckHighScore(const TUint aHighScore)
	{
	TBool addToHSList = EFalse;
	
	SortHighScoreList();
	
	//take last entry in the list
	CHighScoreItem* lastHS = HighScoreItem(MAX_HS_ENTRIES - 1); 

	if (aHighScore > lastHS->HighScore())
		{
		addToHSList = ETrue;
		}

	return addToHSList;	
	}

// End of File  
