/*
* ============================================================================
*  Name     : CTOPGUNView3 from TOPGUNView3.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include  "topgun.hrh"
#include  "TOPGUNView3.h"
#include  "TOPGUNContainer3.h"
#include  "TOPGUNAppUi.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"    

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView3::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CTOPGUNView3::ConstructL(CSndMixer*	aSndMixer,
							  TSample& aMusicSample,
							  TSample& aSelectSample,
							  TSample& aButtonSample,
							  TInt aAudioVol,
							  TInt aSfxVol)
    {
    BaseConstructL();
	iSndMixer = aSndMixer;
	iMusicSample = aMusicSample;
	iSelectSample = aSelectSample;
	iButtonSample = aButtonSample;
	iAudioVol = aAudioVol;
	iSfxVol = aSfxVol;
    }

// ---------------------------------------------------------
// CTOPGUNView3::~CTOPGUNView3()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView3::~CTOPGUNView3()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView3::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView3::Id() const
    {
    return KView5Id;
    }

// ---------------------------------------------------------
// CTOPGUNView3::HandleCommandL(TInt aCommand)
// takes care of View3 command handling
// ---------------------------------------------------------
//
void CTOPGUNView3::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView3::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView3::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView3::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView3::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer3;
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect(),
								iSndMixer,
								iMusicSample,
								iSelectSample,
								iButtonSample,
								iAudioVol,
								iSfxVol);
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
		iContainer->SetVolumeForContainer(iSfxVol,iAudioVol);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView3::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView3::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ---------------------------------------------------------
// CTOPGUNView3::SetAppUi(CTOPGUNAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
void CTOPGUNView3::SetAppUi(CTOPGUNAppUi* aAppUi)
	{
	iAppUi = aAppUi;
	}

// ----------------------------------------------------
// CTOPGUNView3::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView3::SwitchView(TInt aIndex)
	{
	if (iAppUi)
		{
		iAppUi->SwitchView(aIndex);	
		}
	}

// ----------------------------------------------------
// CTOPGUNView3::SetVolume(TInt aSfxVol,TInt aAudioVol)
// 
// ----------------------------------------------------
//
void CTOPGUNView3::SetVolume(TInt aSfxVol,TInt aAudioVol)
	{
	iSfxVol = aSfxVol;
	iAudioVol = aAudioVol;
	if (iAppUi)
		{
		iAppUi->SetVolume(aSfxVol,aAudioVol,EFalse);
		}
	}

void CTOPGUNView3::SetVolumeForContainer(TInt aSfxVol,TInt aAudioVol)
	{
	iSfxVol = aSfxVol;
	iAudioVol = aAudioVol;	
	}



// End of File

