/*
* ============================================================================
*  Name     : CTOPGUNView2 from TOPGUNView2.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: P&P
* ============================================================================
*/

// INCLUDE FILES
#include <aknviewappui.h>
#include <avkon.hrh>
#include <TOPGUN.rsg>
#include "TOPGUNView2.h"
#include "TOPGUNContainer2.h"
#include "TOPGUNAppUi.h"
#include "LevelLoader.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"     

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView2::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//

CTOPGUNView2::CTOPGUNView2(CSndMixer& aSndMixer,
					 TSample& aMusic,
					 TSample& aShotSound,
					 TSample& aExplosionSound,
					 TInt aAudioVol,
					 TInt aSfxVol,
					 CLevelLoader& aLevelLoader,
					 CTOPGUNAppUi& aAppUi):
	iSndMixer(aSndMixer),
	iMusic(aMusic),
	iShotSound(aShotSound),
	iExplosionSound(aExplosionSound),
	iAudioVol(aAudioVol),
	iSfxVol(aSfxVol),
	iLevelLoader(aLevelLoader),
	iAppUi(aAppUi)
	{
	}


void CTOPGUNView2::ConstructL(/*
							  CSndMixer* aSndMixer,
							  TSample& aMusic,
							  TSample& aShotSound,
							  TSample& aExplosionSound,
							  TInt aAudioVol,
							  TInt aSfxVol
							  */)
    {
    BaseConstructL();
	/*
	//iLevelLoader = CLevelLoader::NewL();
	iSndMixer = aSndMixer;
	iMusic = aMusic;
	iShotSound = aShotSound;
	iExplosionSound = aExplosionSound;
	iAudioVol = aAudioVol;
	iSfxVol = aSfxVol;
	*/
    }

// ---------------------------------------------------------
// CTOPGUNView2::~CTOPGUNView2()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView2::~CTOPGUNView2()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
	//delete iLevelLoader;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView2::Id()
// 
// ---------------------------------------------------------
//
TUid CTOPGUNView2::Id() const
    {
    return KView2Id;
    }

// ---------------------------------------------------------
// CTOPGUNView2::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView2::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
        case EAknSoftkeyOk:
            {
            iEikonEnv->InfoMsg( _L("view2 ok") );
            break;
            }
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView2::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView2::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView2::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView2::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer2;
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect(),
								&iSndMixer,
								iMusic,
								iShotSound,
								iExplosionSound,
								iAudioVol,
								iSfxVol,
								&iLevelLoader);
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
		//iContainer->SetVolume(iSfxVal,iAudioVal);
        }
   }

// ---------------------------------------------------------
// CTOPGUNView2::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView2::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

void CTOPGUNView2::StartGameL()
	{
	if (iContainer)
		{
		iContainer->StartGameL();
		}
	}

void CTOPGUNView2::StopGame()
	{
	if (iContainer)
		{
		iContainer->StopGame();
		}
	}

TBool CTOPGUNView2::IsPlaying()
	{
	//change if else to __ASSERT_ALWAYS
	if (iContainer)
		{
		return iContainer->IsPlaying();
		}
	else
		{
		_LIT(KMyPanicDescriptor, "IsPlaying() call from CTOPGUNView2");
		__ASSERT_ALWAYS( 0 ,User::Panic(KMyPanicDescriptor, 0));
		}
	// just to remove the warning
	return EFalse;
	}

void CTOPGUNView2::SetVolume(TInt aSfxVol,TInt aAudioVol)
	{
	iSfxVol = aSfxVol;
	iAudioVol = aAudioVol;
	iAppUi.SetVolume(aSfxVol, aAudioVol, ETrue);//from engine
	}

// ----------------------------------------------------
// CTOPGUNView2::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView2::SwitchView(TInt aIndex)
	{
	iAppUi.SwitchView(aIndex);	
	}

// ---------------------------------------------------------
// CTOPGUNView2::SetAppUi(CTOPGUNAppUi* aAppUi)
// 
// ---------------------------------------------------------
//
/*
void CTOPGUNView2::SetAppUi(CTOPGUNAppUi* aAppUi)
	{
	iAppUi = aAppUi;
	//iAppUi->SetLevelLoader(iLevelLoader);
	}
*/
// End of File

