/*
* ============================================================================
*  Name     : CTOPGUNView7 from TOPGUNView7.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include  "topgun.hrh"
#include  "TOPGUNView7.h"
#include  "TOPGUNContainer7.h"
#include  "TOPGUNAppUi.h"
//sound
#include "CSndMixer.h"
#include "CWavLoader.h"  

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView7::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
CTOPGUNView7::CTOPGUNView7(CLevelLoader& aLevelLoader,
						   CTOPGUNAppUi& aAppUi):
	iLevelLoader(aLevelLoader),
	iAppUi(aAppUi)
	{
	BaseConstructL();
	}

// ---------------------------------------------------------
// CTOPGUNView7::~CTOPGUNView7()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView7::~CTOPGUNView7()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView7::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView7::Id() const
    {
    return KView9Id;
    }

// ---------------------------------------------------------
// CTOPGUNView7::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView7::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView7::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView7::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView7::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView7::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
		iContainer = new (ELeave) CTOPGUNContainer7 (iLevelLoader,iAppUi);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect());
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView7::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView7::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }


// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView7::SwitchView(TInt aIndex)
	{
	iAppUi.SwitchView(aIndex);	
	}


// End of File

