/*
* ============================================================================
*  Name     : CTOPGUNView8 from TOPGUNView8.h
*  Part of  : TOPGUN
*  Created  : 5/9/2004 by pawel@wapice.com
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  : 1.0
*  Copyright: IlPadrino group.
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
//commands
#include  <TOPGUN.rsg>
#include  "topgun.hrh"
#include  "TOPGUNView8.h"
#include  "TOPGUNContainer8.h"
#include  "TOPGUNAppUi.h"
//level loader
#include "LevelLoader.h" 

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CTOPGUNView9::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
CTOPGUNView8::CTOPGUNView8(CLevelLoader& aLevelLoader,
						   CTOPGUNAppUi& aAppUi):
	iLevelLoader(aLevelLoader),
	iAppUi(aAppUi)
	{
	BaseConstructL();
	}

// ---------------------------------------------------------
// CTOPGUNView8::~CTOPGUNView8()
// destructor
// ---------------------------------------------------------
//
CTOPGUNView8::~CTOPGUNView8()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CTOPGUNView8::Id()
//
// ---------------------------------------------------------
//
TUid CTOPGUNView8::Id() const
    {
    return KView10Id;
    }

// ---------------------------------------------------------
// CTOPGUNView8::HandleCommandL(TInt aCommand)
// takes care of view command handling
// ---------------------------------------------------------
//
void CTOPGUNView8::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
		case EStartGame:
			AppUi()->HandleCommandL(EStartGame);
			break;
        case EAknSoftkeyBack:
            {
            //AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CTOPGUNView8::HandleClientRectChange()
// ---------------------------------------------------------
//
void CTOPGUNView8::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CTOPGUNView8::DoActivateL(...)
// 
// ---------------------------------------------------------
//
void CTOPGUNView8::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CTOPGUNContainer8 (iLevelLoader,iAppUi);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( AppUi()->ApplicationRect());
        AppUi()->AddToStackL( *this, iContainer );
		iContainer->SetView(this);
        } 
   }

// ---------------------------------------------------------
// CTOPGUNView8::DoDeactivate()
// 
// ---------------------------------------------------------
//
void CTOPGUNView8::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// ----------------------------------------------------
// CTOPGUNView::SwitchView(TInt aIndex)
// 
// ----------------------------------------------------
//
void CTOPGUNView8::SwitchView(TInt aIndex)
	{
	iAppUi.SwitchView(aIndex);	
	}


// End of File

